### ISSUE TITLE
Incude libfreeimage-3.17.0.so

### ISSUE THREAD

**Issue by CShepartd** [matgr1/FreeImage-dotnet-core#7]
Why not included libfreeimage-3.17.0.so (and others) like in https://github.com/MonoGame/MonoGame.Dependencies/tree/master/FreeImage.NET

Then it can be fully self-container deployment in .Net Core

Tested with my private fork this project and working. For example
```
public static FIBITMAP LoadU(FREE_IMAGE_FORMAT fif, string filename, FREE_IMAGE_LOAD_FLAGS flags)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                return LoadUWindows(fif, filename, flags);
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                return LoadULinux(fif, filename, flags);
            else
                throw new NotSupportedException();
        }
```

**Comment by matgr1** [comment]
thanks for the suggestion, just got it working (I think) in 4.3.0 for Ubuntu and OSX, let me know if there are any issues...

I ended up building the library myself for Ubuntu since the one installed using apt-get doesn't include a couple of dependencies in the library (it installs them as separate libraries instead)

For OSX I just grabbed the dylib that was installed by "brew install freeimage" and that seems to work.

If any other runtimes are required, I'd definitely accept pull requests!
